### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by pmilanez** [nashjain/feedback360#1]
I've deployed this app on heroku to test and the inside links are returning not found. 

http://qulture360.herokuapp.com/survey/create

Is there anything i need to do?

Thanks

**Comment by nashjain** [comment]
Thanks for trying out feedback360. 
Before deploying the app, please complete the following 2 steps:
1. Rename production_example.conf.php to production.conf.php and update the properties inside it.
2. After you've installed Composer (https://getcomposer.org/doc/00-intro.md), from the project's root director run: composer update

I've updated the ReadMe file with the same.

**Comment by pmilanez** [comment]
I did everything and the app is running http://qulture360.herokuapp.com but the internal pages are returning not found. Is there any config needed on the php?

**Comment by pmilanez** [comment]
Solved! My mistake. For some reason the .htacess was out. Fixed! Thanks!! :)
